name: Android CI (develop)

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  lint_and_unittest:
    name: Lint and Unit testsuite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Run Lint
        run: |
          ./gradlew lint

      - name: Run Unit Test
        run: |
          ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}


  instrumentation_test:
    name: Instrumentation testsuite
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: |
        chmod +x ./gradlew
        
    - name: Run Instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2.15.0
      with:
        working-directory: .
        api-level: 29
        script: ./gradlew connectedCheck

